---
  - name: Deploy docker + pihole
    hosts: raspberry-pi
    connection: local
    gather_facts: no
    become: true

    tasks:
      - name: repo key install
        apt_key:
          url: https://download.docker.com/linux/raspbian/gpg
          state: present

      - name: docker registry is installing
        apt_repository: repo='deb https://download.docker.com/linux/raspbian/ buster stable'

      - name: install docker
        package:
          name: docker-ce
          state: present

      - name: starting docker service
        service:
          name: docker
          state: started



